### ISSUE TITLE
add browser support info

### ISSUE THREAD

**Issue by androidfanboi** [filipdanic/json2csvexporter#2]
can you add browser support info? i want to know if i can use this with IE8 and mobile browsers!

**Comment by filipdanic** [comment]
No idea honestly. http://jscc.info/ is showing >95% support on the compiled code. It seems that it works on IE9+. With polyfills for some methods, it can work for IE5-IE8. I will try to look into this when I have some free time.

If you or anyone else get a chance to see which browsers are supported, please submit a PR with the info in the docs! :)

**Comment by androidfanboi** [comment]
works in opera, ms edge, and ie11

good enough for my use case 😇

**Comment by filipdanic** [comment]
To anyone interested in taking this (cc @bira91), here’s what we could use:

The compiled code is available in these two files 

1. https://unpkg.com/json2csvexporter@0.2.4/lib/WriterService.js
2. https://unpkg.com/json2csvexporter@0.2.4/lib/CSVExportService.js

Run these through http://jscc.info/ and take note of which is the lowest common version of IE/Edge/Firefox/Safari/Chrome/Opera that has full support.

Then create a new entry in the README (below the API and Options Docs section) that lists this information.

It would be awesome to add a table like this one: https://godban.github.io/browsers-support-badges/

**Comment by filipdanic** [comment]
Thanks for taking this one @bira91! 👍
