### ISSUE TITLE
Make an online demo

### ISSUE THREAD

**Issue by filipdanic** [filipdanic/json2csvexporter#3]
An online demo of json2csvexporter would be terrific. 

Nothing major, just some code sandbox where people can see a simple HTML table and click on a button that will download that content as CSV. 

We can use something simple like Codepen, Code Sandbox or JSFiddle. I’ll gladly tweak it after it’s been set up.

If you decide to take this task and want to claim credit for Hacktoberfest, just add your username to the contributor list at the bottom of the README and submit that as a PR.

**Comment by erickzhao** [comment]
Hey @filipdanic, I'd be interested in taking over!

**Comment by filipdanic** [comment]
Awesome @erickzhao, go for it! :)
